/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_PIPE = 4,
  sym_variable_symbol = 5,
  sym_procedure_name = 6,
  anon_sym_AT = 7,
  anon_sym_BANG = 8,
  anon_sym_GT = 9,
  anon_sym_CARET = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_double_quoted_terminal_token1 = 12,
  aux_sym_double_quoted_terminal_token2 = 13,
  aux_sym_double_quoted_terminal_token3 = 14,
  aux_sym_double_quoted_terminal_token4 = 15,
  sym_raw_quote_terminal = 16,
  anon_sym_lowercase_letter = 17,
  anon_sym_uppercase_letter = 18,
  anon_sym_block_start = 19,
  anon_sym_block_end = 20,
  anon_sym_whitespace = 21,
  anon_sym_punctuation = 22,
  anon_sym_character = 23,
  anon_sym_operator = 24,
  anon_sym_new_line = 25,
  anon_sym_digit = 26,
  anon_sym_hex_digit = 27,
  anon_sym_letter = 28,
  anon_sym_space = 29,
  anon_sym_utf8_lead_two = 30,
  anon_sym_utf8_lead_three_general = 31,
  anon_sym_utf8_lead_four_general = 32,
  anon_sym_utf8_continuation = 33,
  anon_sym_utf8_continuation_80_8f = 34,
  anon_sym_utf8_continuation_80_9f = 35,
  anon_sym_utf8_continuation_90_bf = 36,
  anon_sym_utf8_continuation_a0_bf = 37,
  sym_source_file = 38,
  sym_comment = 39,
  sym_rule = 40,
  sym_alternative = 41,
  sym_rhs = 42,
  sym_symbol_with_procedure = 43,
  sym_annotation = 44,
  sym_recovery_point = 45,
  sym_verbatim_marker = 46,
  sym_double_quoted_terminal = 47,
  sym_generative_terminal = 48,
  sym_generative_name = 49,
  sym_exception = 50,
  sym_terminal = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_rule_repeat1 = 53,
  aux_sym_rule_repeat2 = 54,
  aux_sym_rhs_repeat1 = 55,
  aux_sym_double_quoted_terminal_repeat1 = 56,
  aux_sym_generative_terminal_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_PIPE] = "|",
  [sym_variable_symbol] = "variable_symbol",
  [sym_procedure_name] = "procedure_name",
  [anon_sym_AT] = "@",
  [anon_sym_BANG] = "!",
  [anon_sym_GT] = ">",
  [anon_sym_CARET] = "^",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_quoted_terminal_token1] = "double_quoted_terminal_token1",
  [aux_sym_double_quoted_terminal_token2] = "double_quoted_terminal_token2",
  [aux_sym_double_quoted_terminal_token3] = "double_quoted_terminal_token3",
  [aux_sym_double_quoted_terminal_token4] = "double_quoted_terminal_token4",
  [sym_raw_quote_terminal] = "raw_quote_terminal",
  [anon_sym_lowercase_letter] = "lowercase_letter",
  [anon_sym_uppercase_letter] = "uppercase_letter",
  [anon_sym_block_start] = "block_start",
  [anon_sym_block_end] = "block_end",
  [anon_sym_whitespace] = "whitespace",
  [anon_sym_punctuation] = "punctuation",
  [anon_sym_character] = "character",
  [anon_sym_operator] = "operator",
  [anon_sym_new_line] = "new_line",
  [anon_sym_digit] = "digit",
  [anon_sym_hex_digit] = "hex_digit",
  [anon_sym_letter] = "letter",
  [anon_sym_space] = "space",
  [anon_sym_utf8_lead_two] = "utf8_lead_two",
  [anon_sym_utf8_lead_three_general] = "utf8_lead_three_general",
  [anon_sym_utf8_lead_four_general] = "utf8_lead_four_general",
  [anon_sym_utf8_continuation] = "utf8_continuation",
  [anon_sym_utf8_continuation_80_8f] = "utf8_continuation_80_8f",
  [anon_sym_utf8_continuation_80_9f] = "utf8_continuation_80_9f",
  [anon_sym_utf8_continuation_90_bf] = "utf8_continuation_90_bf",
  [anon_sym_utf8_continuation_a0_bf] = "utf8_continuation_a0_bf",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_rule] = "rule",
  [sym_alternative] = "alternative",
  [sym_rhs] = "rhs",
  [sym_symbol_with_procedure] = "symbol_with_procedure",
  [sym_annotation] = "annotation",
  [sym_recovery_point] = "recovery_point",
  [sym_verbatim_marker] = "verbatim_marker",
  [sym_double_quoted_terminal] = "double_quoted_terminal",
  [sym_generative_terminal] = "generative_terminal",
  [sym_generative_name] = "generative_name",
  [sym_exception] = "exception",
  [sym_terminal] = "terminal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_rule_repeat2] = "rule_repeat2",
  [aux_sym_rhs_repeat1] = "rhs_repeat1",
  [aux_sym_double_quoted_terminal_repeat1] = "double_quoted_terminal_repeat1",
  [aux_sym_generative_terminal_repeat1] = "generative_terminal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_variable_symbol] = sym_variable_symbol,
  [sym_procedure_name] = sym_procedure_name,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_quoted_terminal_token1] = aux_sym_double_quoted_terminal_token1,
  [aux_sym_double_quoted_terminal_token2] = aux_sym_double_quoted_terminal_token2,
  [aux_sym_double_quoted_terminal_token3] = aux_sym_double_quoted_terminal_token3,
  [aux_sym_double_quoted_terminal_token4] = aux_sym_double_quoted_terminal_token4,
  [sym_raw_quote_terminal] = sym_raw_quote_terminal,
  [anon_sym_lowercase_letter] = anon_sym_lowercase_letter,
  [anon_sym_uppercase_letter] = anon_sym_uppercase_letter,
  [anon_sym_block_start] = anon_sym_block_start,
  [anon_sym_block_end] = anon_sym_block_end,
  [anon_sym_whitespace] = anon_sym_whitespace,
  [anon_sym_punctuation] = anon_sym_punctuation,
  [anon_sym_character] = anon_sym_character,
  [anon_sym_operator] = anon_sym_operator,
  [anon_sym_new_line] = anon_sym_new_line,
  [anon_sym_digit] = anon_sym_digit,
  [anon_sym_hex_digit] = anon_sym_hex_digit,
  [anon_sym_letter] = anon_sym_letter,
  [anon_sym_space] = anon_sym_space,
  [anon_sym_utf8_lead_two] = anon_sym_utf8_lead_two,
  [anon_sym_utf8_lead_three_general] = anon_sym_utf8_lead_three_general,
  [anon_sym_utf8_lead_four_general] = anon_sym_utf8_lead_four_general,
  [anon_sym_utf8_continuation] = anon_sym_utf8_continuation,
  [anon_sym_utf8_continuation_80_8f] = anon_sym_utf8_continuation_80_8f,
  [anon_sym_utf8_continuation_80_9f] = anon_sym_utf8_continuation_80_9f,
  [anon_sym_utf8_continuation_90_bf] = anon_sym_utf8_continuation_90_bf,
  [anon_sym_utf8_continuation_a0_bf] = anon_sym_utf8_continuation_a0_bf,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_rule] = sym_rule,
  [sym_alternative] = sym_alternative,
  [sym_rhs] = sym_rhs,
  [sym_symbol_with_procedure] = sym_symbol_with_procedure,
  [sym_annotation] = sym_annotation,
  [sym_recovery_point] = sym_recovery_point,
  [sym_verbatim_marker] = sym_verbatim_marker,
  [sym_double_quoted_terminal] = sym_double_quoted_terminal,
  [sym_generative_terminal] = sym_generative_terminal,
  [sym_generative_name] = sym_generative_name,
  [sym_exception] = sym_exception,
  [sym_terminal] = sym_terminal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_rule_repeat2] = aux_sym_rule_repeat2,
  [aux_sym_rhs_repeat1] = aux_sym_rhs_repeat1,
  [aux_sym_double_quoted_terminal_repeat1] = aux_sym_double_quoted_terminal_repeat1,
  [aux_sym_generative_terminal_repeat1] = aux_sym_generative_terminal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_raw_quote_terminal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_lowercase_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uppercase_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block_start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_whitespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_punctuation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_character] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new_line] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_digit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hex_digit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_space] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_lead_two] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_lead_three_general] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_lead_four_general] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_continuation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_continuation_80_8f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_continuation_80_9f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_continuation_90_bf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_utf8_continuation_a0_bf] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_with_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_recovery_point] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_terminal] = {
    .visible = true,
    .named = true,
  },
  [sym_generative_terminal] = {
    .visible = true,
    .named = true,
  },
  [sym_generative_name] = {
    .visible = true,
    .named = true,
  },
  [sym_exception] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rhs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generative_terminal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_annotation = 2,
  field_marker = 3,
  field_name = 4,
  field_point = 5,
  field_procedure = 6,
  field_symbol = 7,
  field_terminal = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_annotation] = "annotation",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_point] = "point",
  [field_procedure] = "procedure",
  [field_symbol] = "symbol",
  [field_terminal] = "terminal",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 1},
  [11] = {.index = 13, .length = 1},
  [12] = {.index = 14, .length = 1},
  [13] = {.index = 15, .length = 3},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 2},
  [16] = {.index = 21, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_annotation, 0},
  [1] =
    {field_alternative, 0},
  [2] =
    {field_alternative, 2, .inherited = true},
    {field_name, 0},
  [4] =
    {field_procedure, 1},
  [5] =
    {field_annotation, 0, .inherited = true},
    {field_annotation, 1, .inherited = true},
  [7] =
    {field_symbol, 0},
  [8] =
    {field_name, 0},
  [9] =
    {field_symbol, 0, .inherited = true},
  [10] =
    {field_alternative, 0, .inherited = true},
    {field_alternative, 1, .inherited = true},
  [12] =
    {field_point, 2},
  [13] =
    {field_marker, 2},
  [14] =
    {field_terminal, 0},
  [15] =
    {field_alternative, 3, .inherited = true},
    {field_annotation, 1, .inherited = true},
    {field_name, 0},
  [18] =
    {field_annotation, 1, .inherited = true},
  [19] =
    {field_symbol, 0, .inherited = true},
    {field_symbol, 1, .inherited = true},
  [21] =
    {field_terminal, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(173);
      ADVANCE_MAP(
        '\n', 174,
        '!', 182,
        '"', 185,
        '#', 175,
        '>', 183,
        '@', 181,
        '\\', 160,
        '^', 184,
        '_', 172,
        'b', 99,
        'c', 86,
        'd', 89,
        'h', 50,
        'l', 51,
        'n', 56,
        'o', 122,
        'p', 161,
        's', 121,
        'u', 123,
        'w', 87,
        '|', 178,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(179);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 174,
        '"', 185,
        '>', 183,
        '@', 181,
        '\\', 4,
        '^', 184,
        '_', 172,
        'b', 99,
        'c', 86,
        'd', 89,
        'h', 50,
        'l', 51,
        'n', 56,
        'o', 122,
        'p', 161,
        's', 121,
        'u', 123,
        'w', 87,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(179);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(182);
      if (lookahead == '>') ADVANCE(183);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(180);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(185);
      if (lookahead == '\\') ADVANCE(160);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(192);
      if (lookahead != 0) ADVANCE(191);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(169);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(193);
      END_STATE();
    case 6:
      if (lookahead == '0') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '0') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == '8') ADVANCE(6);
      if (lookahead == '9') ADVANCE(7);
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '8') ADVANCE(77);
      if (lookahead == '9') ADVANCE(78);
      END_STATE();
    case 11:
      if (lookahead == '8') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == '_') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == '_') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == '_') ADVANCE(58);
      END_STATE();
    case 15:
      if (lookahead == '_') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == '_') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == '_') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == '_') ADVANCE(102);
      END_STATE();
    case 19:
      if (lookahead == '_') ADVANCE(82);
      END_STATE();
    case 20:
      if (lookahead == '_') ADVANCE(103);
      END_STATE();
    case 21:
      if (lookahead == '_') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == '_') ADVANCE(104);
      END_STATE();
    case 23:
      if (lookahead == '_') ADVANCE(85);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(138);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(140);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(100);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(101);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(147);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(136);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(149);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(159);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(142);
      END_STATE();
    case 37:
      if (lookahead == 'b') ADVANCE(79);
      END_STATE();
    case 38:
      if (lookahead == 'b') ADVANCE(80);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(98);
      END_STATE();
    case 40:
      if (lookahead == 'c') ADVANCE(117);
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(146);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(153);
      END_STATE();
    case 46:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(197);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(167);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(148);
      if (lookahead == 'o') ADVANCE(166);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(206);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(141);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(202);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(198);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(165);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(108);
      if (lookahead == 's') ADVANCE(156);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(157);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(158);
      END_STATE();
    case 72:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 76:
      if (lookahead == 'f') ADVANCE(11);
      END_STATE();
    case 77:
      if (lookahead == 'f') ADVANCE(211);
      END_STATE();
    case 78:
      if (lookahead == 'f') ADVANCE(212);
      END_STATE();
    case 79:
      if (lookahead == 'f') ADVANCE(213);
      END_STATE();
    case 80:
      if (lookahead == 'f') ADVANCE(214);
      END_STATE();
    case 81:
      if (lookahead == 'f') ADVANCE(116);
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 82:
      if (lookahead == 'g') ADVANCE(67);
      END_STATE();
    case 83:
      if (lookahead == 'g') ADVANCE(91);
      END_STATE();
    case 84:
      if (lookahead == 'g') ADVANCE(93);
      END_STATE();
    case 85:
      if (lookahead == 'g') ADVANCE(72);
      END_STATE();
    case 86:
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 87:
      if (lookahead == 'h') ADVANCE(94);
      END_STATE();
    case 88:
      if (lookahead == 'h') ADVANCE(137);
      if (lookahead == 'w') ADVANCE(115);
      END_STATE();
    case 89:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(110);
      END_STATE();
    case 91:
      if (lookahead == 'i') ADVANCE(143);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(113);
      END_STATE();
    case 93:
      if (lookahead == 'i') ADVANCE(144);
      END_STATE();
    case 94:
      if (lookahead == 'i') ADVANCE(152);
      END_STATE();
    case 95:
      if (lookahead == 'i') ADVANCE(119);
      END_STATE();
    case 96:
      if (lookahead == 'i') ADVANCE(120);
      END_STATE();
    case 97:
      if (lookahead == 'i') ADVANCE(84);
      END_STATE();
    case 98:
      if (lookahead == 'k') ADVANCE(14);
      END_STATE();
    case 99:
      if (lookahead == 'l') ADVANCE(114);
      END_STATE();
    case 100:
      if (lookahead == 'l') ADVANCE(209);
      END_STATE();
    case 101:
      if (lookahead == 'l') ADVANCE(208);
      END_STATE();
    case 102:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 103:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 104:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 105:
      if (lookahead == 'n') ADVANCE(199);
      END_STATE();
    case 106:
      if (lookahead == 'n') ADVANCE(210);
      END_STATE();
    case 107:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 109:
      if (lookahead == 'n') ADVANCE(150);
      END_STATE();
    case 110:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 112:
      if (lookahead == 'n') ADVANCE(69);
      END_STATE();
    case 113:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 114:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 115:
      if (lookahead == 'o') ADVANCE(207);
      END_STATE();
    case 116:
      if (lookahead == 'o') ADVANCE(162);
      END_STATE();
    case 117:
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 118:
      if (lookahead == 'o') ADVANCE(127);
      END_STATE();
    case 119:
      if (lookahead == 'o') ADVANCE(105);
      END_STATE();
    case 120:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 121:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 122:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 123:
      if (lookahead == 'p') ADVANCE(125);
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 124:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 125:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 126:
      if (lookahead == 'r') ADVANCE(205);
      END_STATE();
    case 127:
      if (lookahead == 'r') ADVANCE(201);
      END_STATE();
    case 128:
      if (lookahead == 'r') ADVANCE(200);
      END_STATE();
    case 129:
      if (lookahead == 'r') ADVANCE(194);
      END_STATE();
    case 130:
      if (lookahead == 'r') ADVANCE(195);
      END_STATE();
    case 131:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 132:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 133:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 134:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 135:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 136:
      if (lookahead == 'r') ADVANCE(145);
      END_STATE();
    case 137:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 138:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 139:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 140:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 141:
      if (lookahead == 's') ADVANCE(124);
      END_STATE();
    case 142:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 143:
      if (lookahead == 't') ADVANCE(203);
      END_STATE();
    case 144:
      if (lookahead == 't') ADVANCE(204);
      END_STATE();
    case 145:
      if (lookahead == 't') ADVANCE(196);
      END_STATE();
    case 146:
      if (lookahead == 't') ADVANCE(163);
      END_STATE();
    case 147:
      if (lookahead == 't') ADVANCE(118);
      END_STATE();
    case 148:
      if (lookahead == 't') ADVANCE(151);
      END_STATE();
    case 149:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 150:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 151:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 152:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 153:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 154:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 155:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 156:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 157:
      if (lookahead == 't') ADVANCE(154);
      END_STATE();
    case 158:
      if (lookahead == 't') ADVANCE(155);
      END_STATE();
    case 159:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 160:
      if (lookahead == 'u') ADVANCE(189);
      if (lookahead == 'x') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 161:
      if (lookahead == 'u') ADVANCE(107);
      END_STATE();
    case 162:
      if (lookahead == 'u') ADVANCE(135);
      END_STATE();
    case 163:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 164:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 165:
      if (lookahead == 'w') ADVANCE(18);
      END_STATE();
    case 166:
      if (lookahead == 'w') ADVANCE(57);
      END_STATE();
    case 167:
      if (lookahead == 'x') ADVANCE(12);
      END_STATE();
    case 168:
      if (lookahead == '}') ADVANCE(186);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(168);
      END_STATE();
    case 169:
      if (lookahead == '~') ADVANCE(170);
      END_STATE();
    case 170:
      if (lookahead == '~') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(170);
      END_STATE();
    case 171:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(168);
      END_STATE();
    case 172:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(179);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(177);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(177);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_variable_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(179);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_procedure_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(180);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token1);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(187);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token3);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token3);
      if (lookahead == '{') ADVANCE(171);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(187);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token4);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(191);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_raw_quote_terminal);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_lowercase_letter);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(anon_sym_uppercase_letter);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_block_start);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_block_end);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_whitespace);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(anon_sym_punctuation);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_character);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_operator);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(anon_sym_new_line);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_digit);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_hex_digit);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_letter);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_space);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_utf8_lead_two);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_utf8_lead_three_general);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_utf8_lead_four_general);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_utf8_continuation);
      if (lookahead == '_') ADVANCE(9);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(anon_sym_utf8_continuation_80_8f);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(anon_sym_utf8_continuation_80_9f);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_utf8_continuation_90_bf);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(anon_sym_utf8_continuation_a0_bf);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 176},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_variable_symbol] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_double_quoted_terminal_token1] = ACTIONS(1),
    [aux_sym_double_quoted_terminal_token2] = ACTIONS(1),
    [aux_sym_double_quoted_terminal_token3] = ACTIONS(1),
    [anon_sym_lowercase_letter] = ACTIONS(1),
    [anon_sym_uppercase_letter] = ACTIONS(1),
    [anon_sym_block_start] = ACTIONS(1),
    [anon_sym_block_end] = ACTIONS(1),
    [anon_sym_whitespace] = ACTIONS(1),
    [anon_sym_punctuation] = ACTIONS(1),
    [anon_sym_character] = ACTIONS(1),
    [anon_sym_operator] = ACTIONS(1),
    [anon_sym_new_line] = ACTIONS(1),
    [anon_sym_digit] = ACTIONS(1),
    [anon_sym_hex_digit] = ACTIONS(1),
    [anon_sym_letter] = ACTIONS(1),
    [anon_sym_space] = ACTIONS(1),
    [anon_sym_utf8_lead_two] = ACTIONS(1),
    [anon_sym_utf8_lead_three_general] = ACTIONS(1),
    [anon_sym_utf8_lead_four_general] = ACTIONS(1),
    [anon_sym_utf8_continuation] = ACTIONS(1),
    [anon_sym_utf8_continuation_80_8f] = ACTIONS(1),
    [anon_sym_utf8_continuation_80_9f] = ACTIONS(1),
    [anon_sym_utf8_continuation_90_bf] = ACTIONS(1),
    [anon_sym_utf8_continuation_a0_bf] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym_comment] = STATE(32),
    [sym_rule] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_variable_symbol] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_rhs] = STATE(54),
    [sym_symbol_with_procedure] = STATE(27),
    [sym_annotation] = STATE(18),
    [sym_double_quoted_terminal] = STATE(9),
    [sym_generative_terminal] = STATE(9),
    [sym_generative_name] = STATE(7),
    [aux_sym_rule_repeat1] = STATE(3),
    [aux_sym_rhs_repeat1] = STATE(4),
    [anon_sym_LF] = ACTIONS(11),
    [sym_variable_symbol] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_raw_quote_terminal] = ACTIONS(13),
    [anon_sym_lowercase_letter] = ACTIONS(19),
    [anon_sym_uppercase_letter] = ACTIONS(19),
    [anon_sym_block_start] = ACTIONS(19),
    [anon_sym_block_end] = ACTIONS(19),
    [anon_sym_whitespace] = ACTIONS(19),
    [anon_sym_punctuation] = ACTIONS(19),
    [anon_sym_character] = ACTIONS(19),
    [anon_sym_operator] = ACTIONS(19),
    [anon_sym_new_line] = ACTIONS(19),
    [anon_sym_digit] = ACTIONS(19),
    [anon_sym_hex_digit] = ACTIONS(19),
    [anon_sym_letter] = ACTIONS(19),
    [anon_sym_space] = ACTIONS(19),
    [anon_sym_utf8_lead_two] = ACTIONS(19),
    [anon_sym_utf8_lead_three_general] = ACTIONS(19),
    [anon_sym_utf8_lead_four_general] = ACTIONS(19),
    [anon_sym_utf8_continuation] = ACTIONS(21),
    [anon_sym_utf8_continuation_80_8f] = ACTIONS(19),
    [anon_sym_utf8_continuation_80_9f] = ACTIONS(19),
    [anon_sym_utf8_continuation_90_bf] = ACTIONS(19),
    [anon_sym_utf8_continuation_a0_bf] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_rhs] = STATE(55),
    [sym_symbol_with_procedure] = STATE(27),
    [sym_annotation] = STATE(18),
    [sym_double_quoted_terminal] = STATE(9),
    [sym_generative_terminal] = STATE(9),
    [sym_generative_name] = STATE(7),
    [aux_sym_rule_repeat1] = STATE(10),
    [aux_sym_rhs_repeat1] = STATE(4),
    [anon_sym_LF] = ACTIONS(23),
    [sym_variable_symbol] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_raw_quote_terminal] = ACTIONS(13),
    [anon_sym_lowercase_letter] = ACTIONS(19),
    [anon_sym_uppercase_letter] = ACTIONS(19),
    [anon_sym_block_start] = ACTIONS(19),
    [anon_sym_block_end] = ACTIONS(19),
    [anon_sym_whitespace] = ACTIONS(19),
    [anon_sym_punctuation] = ACTIONS(19),
    [anon_sym_character] = ACTIONS(19),
    [anon_sym_operator] = ACTIONS(19),
    [anon_sym_new_line] = ACTIONS(19),
    [anon_sym_digit] = ACTIONS(19),
    [anon_sym_hex_digit] = ACTIONS(19),
    [anon_sym_letter] = ACTIONS(19),
    [anon_sym_space] = ACTIONS(19),
    [anon_sym_utf8_lead_two] = ACTIONS(19),
    [anon_sym_utf8_lead_three_general] = ACTIONS(19),
    [anon_sym_utf8_lead_four_general] = ACTIONS(19),
    [anon_sym_utf8_continuation] = ACTIONS(21),
    [anon_sym_utf8_continuation_80_8f] = ACTIONS(19),
    [anon_sym_utf8_continuation_80_9f] = ACTIONS(19),
    [anon_sym_utf8_continuation_90_bf] = ACTIONS(19),
    [anon_sym_utf8_continuation_a0_bf] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_symbol_with_procedure] = STATE(27),
    [sym_double_quoted_terminal] = STATE(9),
    [sym_generative_terminal] = STATE(9),
    [sym_generative_name] = STATE(7),
    [aux_sym_rhs_repeat1] = STATE(5),
    [anon_sym_LF] = ACTIONS(25),
    [sym_variable_symbol] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_raw_quote_terminal] = ACTIONS(13),
    [anon_sym_lowercase_letter] = ACTIONS(19),
    [anon_sym_uppercase_letter] = ACTIONS(19),
    [anon_sym_block_start] = ACTIONS(19),
    [anon_sym_block_end] = ACTIONS(19),
    [anon_sym_whitespace] = ACTIONS(19),
    [anon_sym_punctuation] = ACTIONS(19),
    [anon_sym_character] = ACTIONS(19),
    [anon_sym_operator] = ACTIONS(19),
    [anon_sym_new_line] = ACTIONS(19),
    [anon_sym_digit] = ACTIONS(19),
    [anon_sym_hex_digit] = ACTIONS(19),
    [anon_sym_letter] = ACTIONS(19),
    [anon_sym_space] = ACTIONS(19),
    [anon_sym_utf8_lead_two] = ACTIONS(19),
    [anon_sym_utf8_lead_three_general] = ACTIONS(19),
    [anon_sym_utf8_lead_four_general] = ACTIONS(19),
    [anon_sym_utf8_continuation] = ACTIONS(21),
    [anon_sym_utf8_continuation_80_8f] = ACTIONS(19),
    [anon_sym_utf8_continuation_80_9f] = ACTIONS(19),
    [anon_sym_utf8_continuation_90_bf] = ACTIONS(19),
    [anon_sym_utf8_continuation_a0_bf] = ACTIONS(19),
  },
  [STATE(5)] = {
    [sym_symbol_with_procedure] = STATE(27),
    [sym_double_quoted_terminal] = STATE(9),
    [sym_generative_terminal] = STATE(9),
    [sym_generative_name] = STATE(7),
    [aux_sym_rhs_repeat1] = STATE(5),
    [anon_sym_LF] = ACTIONS(27),
    [sym_variable_symbol] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(32),
    [sym_raw_quote_terminal] = ACTIONS(29),
    [anon_sym_lowercase_letter] = ACTIONS(35),
    [anon_sym_uppercase_letter] = ACTIONS(35),
    [anon_sym_block_start] = ACTIONS(35),
    [anon_sym_block_end] = ACTIONS(35),
    [anon_sym_whitespace] = ACTIONS(35),
    [anon_sym_punctuation] = ACTIONS(35),
    [anon_sym_character] = ACTIONS(35),
    [anon_sym_operator] = ACTIONS(35),
    [anon_sym_new_line] = ACTIONS(35),
    [anon_sym_digit] = ACTIONS(35),
    [anon_sym_hex_digit] = ACTIONS(35),
    [anon_sym_letter] = ACTIONS(35),
    [anon_sym_space] = ACTIONS(35),
    [anon_sym_utf8_lead_two] = ACTIONS(35),
    [anon_sym_utf8_lead_three_general] = ACTIONS(35),
    [anon_sym_utf8_lead_four_general] = ACTIONS(35),
    [anon_sym_utf8_continuation] = ACTIONS(38),
    [anon_sym_utf8_continuation_80_8f] = ACTIONS(35),
    [anon_sym_utf8_continuation_80_9f] = ACTIONS(35),
    [anon_sym_utf8_continuation_90_bf] = ACTIONS(35),
    [anon_sym_utf8_continuation_a0_bf] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(43), 1,
      anon_sym_CARET,
    ACTIONS(46), 1,
      anon_sym_utf8_continuation,
    STATE(6), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(41), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [38] = 4,
    ACTIONS(50), 1,
      anon_sym_CARET,
    ACTIONS(52), 1,
      anon_sym_utf8_continuation,
    STATE(8), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(48), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [76] = 4,
    ACTIONS(50), 1,
      anon_sym_CARET,
    ACTIONS(56), 1,
      anon_sym_utf8_continuation,
    STATE(6), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(54), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [114] = 5,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(60), 1,
      anon_sym_utf8_continuation,
    STATE(11), 1,
      aux_sym_rule_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(58), 24,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [153] = 5,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(67), 1,
      anon_sym_utf8_continuation,
    STATE(10), 1,
      aux_sym_rule_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(62), 24,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [192] = 5,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(71), 1,
      anon_sym_utf8_continuation,
    STATE(10), 1,
      aux_sym_rule_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(69), 24,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [231] = 2,
    ACTIONS(75), 1,
      anon_sym_utf8_continuation,
    ACTIONS(73), 26,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [263] = 2,
    ACTIONS(79), 1,
      anon_sym_utf8_continuation,
    ACTIONS(77), 26,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [295] = 2,
    ACTIONS(83), 1,
      anon_sym_utf8_continuation,
    ACTIONS(81), 26,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [327] = 3,
    ACTIONS(87), 1,
      anon_sym_CARET,
    ACTIONS(89), 1,
      anon_sym_utf8_continuation,
    ACTIONS(85), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [361] = 2,
    ACTIONS(93), 1,
      anon_sym_utf8_continuation,
    ACTIONS(91), 26,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [393] = 2,
    ACTIONS(97), 1,
      anon_sym_utf8_continuation,
    ACTIONS(95), 26,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_CARET,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [425] = 2,
    ACTIONS(101), 1,
      anon_sym_utf8_continuation,
    ACTIONS(99), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [456] = 2,
    ACTIONS(105), 1,
      anon_sym_utf8_continuation,
    ACTIONS(103), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [487] = 2,
    ACTIONS(109), 1,
      anon_sym_utf8_continuation,
    ACTIONS(107), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [518] = 2,
    ACTIONS(113), 1,
      anon_sym_utf8_continuation,
    ACTIONS(111), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [549] = 2,
    ACTIONS(117), 1,
      anon_sym_utf8_continuation,
    ACTIONS(115), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [580] = 2,
    ACTIONS(121), 1,
      anon_sym_utf8_continuation,
    ACTIONS(119), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [611] = 2,
    ACTIONS(125), 1,
      anon_sym_utf8_continuation,
    ACTIONS(123), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [642] = 2,
    ACTIONS(129), 1,
      anon_sym_utf8_continuation,
    ACTIONS(127), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [673] = 2,
    ACTIONS(133), 1,
      anon_sym_utf8_continuation,
    ACTIONS(131), 25,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [704] = 2,
    ACTIONS(137), 1,
      anon_sym_utf8_continuation,
    ACTIONS(135), 24,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      sym_raw_quote_terminal,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_hex_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_utf8_lead_two,
      anon_sym_utf8_lead_three_general,
      anon_sym_utf8_lead_four_general,
      anon_sym_utf8_continuation_80_8f,
      anon_sym_utf8_continuation_80_9f,
      anon_sym_utf8_continuation_90_bf,
      anon_sym_utf8_continuation_a0_bf,
  [734] = 6,
    ACTIONS(141), 1,
      anon_sym_LF,
    ACTIONS(144), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      sym_alternative,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(28), 2,
      sym_comment,
      aux_sym_rule_repeat2,
  [755] = 6,
    ACTIONS(152), 1,
      anon_sym_LF,
    ACTIONS(155), 1,
      anon_sym_POUND,
    ACTIONS(158), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      sym_alternative,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(28), 2,
      sym_comment,
      aux_sym_rule_repeat2,
  [776] = 6,
    ACTIONS(158), 1,
      anon_sym_PIPE,
    ACTIONS(162), 1,
      anon_sym_LF,
    ACTIONS(165), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_alternative,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(28), 2,
      sym_comment,
      aux_sym_rule_repeat2,
  [797] = 7,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(168), 1,
      anon_sym_GT,
    ACTIONS(170), 1,
      anon_sym_CARET,
    ACTIONS(172), 1,
      sym_raw_quote_terminal,
    STATE(13), 1,
      sym_double_quoted_terminal,
    STATE(15), 1,
      sym_terminal,
    STATE(22), 1,
      sym_verbatim_marker,
  [819] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_variable_symbol,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    ACTIONS(176), 1,
      anon_sym_LF,
    STATE(33), 3,
      sym_comment,
      sym_rule,
      aux_sym_source_file_repeat1,
  [837] = 5,
    ACTIONS(178), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      anon_sym_LF,
    ACTIONS(183), 1,
      anon_sym_POUND,
    ACTIONS(186), 1,
      sym_variable_symbol,
    STATE(33), 3,
      sym_comment,
      sym_rule,
      aux_sym_source_file_repeat1,
  [855] = 4,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 1,
      aux_sym_double_quoted_terminal_token4,
    STATE(38), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(191), 3,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
      aux_sym_double_quoted_terminal_token3,
  [870] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(158), 1,
      anon_sym_PIPE,
    ACTIONS(195), 1,
      anon_sym_LF,
    STATE(43), 1,
      sym_alternative,
    STATE(29), 2,
      sym_comment,
      aux_sym_rule_repeat2,
  [887] = 6,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      sym_raw_quote_terminal,
    ACTIONS(197), 1,
      anon_sym_CARET,
    STATE(13), 1,
      sym_double_quoted_terminal,
    STATE(20), 1,
      sym_recovery_point,
    STATE(52), 1,
      sym_terminal,
  [906] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(158), 1,
      anon_sym_PIPE,
    ACTIONS(199), 1,
      anon_sym_LF,
    STATE(43), 1,
      sym_alternative,
    STATE(30), 2,
      sym_comment,
      aux_sym_rule_repeat2,
  [923] = 4,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 1,
      aux_sym_double_quoted_terminal_token4,
    STATE(38), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(203), 3,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
      aux_sym_double_quoted_terminal_token3,
  [938] = 4,
    ACTIONS(209), 1,
      anon_sym_DQUOTE,
    ACTIONS(213), 1,
      aux_sym_double_quoted_terminal_token4,
    STATE(34), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(211), 3,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
      aux_sym_double_quoted_terminal_token3,
  [953] = 1,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [961] = 1,
    ACTIONS(217), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [969] = 1,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [977] = 1,
    ACTIONS(221), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [985] = 1,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [993] = 1,
    ACTIONS(225), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [1001] = 4,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      sym_raw_quote_terminal,
    STATE(13), 1,
      sym_double_quoted_terminal,
    STATE(23), 1,
      sym_terminal,
  [1014] = 4,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      sym_raw_quote_terminal,
    STATE(13), 1,
      sym_double_quoted_terminal,
    STATE(25), 1,
      sym_terminal,
  [1027] = 4,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      sym_raw_quote_terminal,
    STATE(13), 1,
      sym_double_quoted_terminal,
    STATE(17), 1,
      sym_terminal,
  [1040] = 4,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(227), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_annotation,
    STATE(50), 1,
      aux_sym_rule_repeat1,
  [1053] = 4,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(229), 1,
      anon_sym_LF,
    STATE(10), 1,
      aux_sym_rule_repeat1,
    STATE(18), 1,
      sym_annotation,
  [1066] = 3,
    ACTIONS(231), 1,
      sym_procedure_name,
    ACTIONS(233), 1,
      anon_sym_BANG,
    ACTIONS(235), 1,
      anon_sym_GT,
  [1076] = 1,
    ACTIONS(237), 1,
      anon_sym_CARET,
  [1080] = 1,
    ACTIONS(239), 1,
      aux_sym_comment_token1,
  [1084] = 1,
    ACTIONS(241), 1,
      anon_sym_LF,
  [1088] = 1,
    ACTIONS(243), 1,
      anon_sym_LF,
  [1092] = 1,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 38,
  [SMALL_STATE(8)] = 76,
  [SMALL_STATE(9)] = 114,
  [SMALL_STATE(10)] = 153,
  [SMALL_STATE(11)] = 192,
  [SMALL_STATE(12)] = 231,
  [SMALL_STATE(13)] = 263,
  [SMALL_STATE(14)] = 295,
  [SMALL_STATE(15)] = 327,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 393,
  [SMALL_STATE(18)] = 425,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 487,
  [SMALL_STATE(21)] = 518,
  [SMALL_STATE(22)] = 549,
  [SMALL_STATE(23)] = 580,
  [SMALL_STATE(24)] = 611,
  [SMALL_STATE(25)] = 642,
  [SMALL_STATE(26)] = 673,
  [SMALL_STATE(27)] = 704,
  [SMALL_STATE(28)] = 734,
  [SMALL_STATE(29)] = 755,
  [SMALL_STATE(30)] = 776,
  [SMALL_STATE(31)] = 797,
  [SMALL_STATE(32)] = 819,
  [SMALL_STATE(33)] = 837,
  [SMALL_STATE(34)] = 855,
  [SMALL_STATE(35)] = 870,
  [SMALL_STATE(36)] = 887,
  [SMALL_STATE(37)] = 906,
  [SMALL_STATE(38)] = 923,
  [SMALL_STATE(39)] = 938,
  [SMALL_STATE(40)] = 953,
  [SMALL_STATE(41)] = 961,
  [SMALL_STATE(42)] = 969,
  [SMALL_STATE(43)] = 977,
  [SMALL_STATE(44)] = 985,
  [SMALL_STATE(45)] = 993,
  [SMALL_STATE(46)] = 1001,
  [SMALL_STATE(47)] = 1014,
  [SMALL_STATE(48)] = 1027,
  [SMALL_STATE(49)] = 1040,
  [SMALL_STATE(50)] = 1053,
  [SMALL_STATE(51)] = 1066,
  [SMALL_STATE(52)] = 1076,
  [SMALL_STATE(53)] = 1080,
  [SMALL_STATE(54)] = 1084,
  [SMALL_STATE(55)] = 1088,
  [SMALL_STATE(56)] = 1092,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rhs, 1, 0, 8),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 15),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 15), SHIFT_REPEAT(9),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 15), SHIFT_REPEAT(39),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 15), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 15), SHIFT_REPEAT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generative_terminal_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generative_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_generative_terminal_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_terminal, 1, 0, 7),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generative_terminal, 1, 0, 7),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_terminal, 2, 0, 7),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generative_terminal, 2, 0, 7),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_with_procedure, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_with_procedure, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 5),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 5), SHIFT_REPEAT(51),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_with_procedure, 2, 0, 14),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol_with_procedure, 2, 0, 14),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_name, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generative_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_terminal, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_terminal, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quoted_terminal, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_marker, 1, 0, 12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_marker, 1, 0, 12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_terminal, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quoted_terminal, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exception, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exception, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 1, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 1, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2, 0, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 2, 0, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 3, 0, 10),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 3, 0, 10),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_marker, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_marker, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 3, 0, 11),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 3, 0, 11),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recovery_point, 2, 0, 16),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recovery_point, 2, 0, 16),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recovery_point, 2, 0, 12),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recovery_point, 2, 0, 12),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_marker, 2, 0, 16),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_marker, 2, 0, 16),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_marker, 2, 0, 12),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verbatim_marker, 2, 0, 12),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 1, 0, 6),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_rhs_repeat1, 1, 0, 6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 9),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 9), SHIFT_REPEAT(28),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 9), SHIFT_REPEAT(53),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 2, 0, 9), SHIFT_REPEAT(2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3), SHIFT(28),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3), SHIFT(53),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 13),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 4, 0, 13), SHIFT(28),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 4, 0, 13), SHIFT(53),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat2, 1, 0, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3, 0, 14),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 4, 0, 14),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [245] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_galley(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "galley",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
