/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_POUND = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_PIPE = 4,
  sym_variable_symbol = 5,
  anon_sym_AT = 6,
  sym_procedure_name = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_double_quoted_terminal_token1 = 9,
  aux_sym_double_quoted_terminal_token2 = 10,
  aux_sym_double_quoted_terminal_token3 = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_single_quoted_terminal_token1 = 13,
  anon_sym_ETX = 14,
  anon_sym_lowercase_letter = 15,
  anon_sym_uppercase_letter = 16,
  anon_sym_block_start = 17,
  anon_sym_block_end = 18,
  anon_sym_whitespace = 19,
  anon_sym_punctuation = 20,
  anon_sym_character = 21,
  anon_sym_operator = 22,
  anon_sym_new_line = 23,
  anon_sym_digit = 24,
  anon_sym_letter = 25,
  anon_sym_space = 26,
  anon_sym_CARET = 27,
  sym_source_file = 28,
  sym_comment = 29,
  sym_rule = 30,
  sym_alternative = 31,
  sym_rhs = 32,
  sym_symbol_with_procedure = 33,
  sym_procedure_tail = 34,
  sym_double_quoted_terminal = 35,
  sym_single_quoted_terminal = 36,
  sym_generative_terminal = 37,
  sym_generative_name = 38,
  sym_exception = 39,
  sym_terminal = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_rule_repeat1 = 42,
  aux_sym_rhs_repeat1 = 43,
  aux_sym_procedure_tail_repeat1 = 44,
  aux_sym_double_quoted_terminal_repeat1 = 45,
  aux_sym_single_quoted_terminal_repeat1 = 46,
  aux_sym_generative_terminal_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_PIPE] = "|",
  [sym_variable_symbol] = "variable_symbol",
  [anon_sym_AT] = "@",
  [sym_procedure_name] = "procedure_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_quoted_terminal_token1] = "double_quoted_terminal_token1",
  [aux_sym_double_quoted_terminal_token2] = "double_quoted_terminal_token2",
  [aux_sym_double_quoted_terminal_token3] = "double_quoted_terminal_token3",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_quoted_terminal_token1] = "single_quoted_terminal_token1",
  [anon_sym_ETX] = "\x03",
  [anon_sym_lowercase_letter] = "lowercase_letter",
  [anon_sym_uppercase_letter] = "uppercase_letter",
  [anon_sym_block_start] = "block_start",
  [anon_sym_block_end] = "block_end",
  [anon_sym_whitespace] = "whitespace",
  [anon_sym_punctuation] = "punctuation",
  [anon_sym_character] = "character",
  [anon_sym_operator] = "operator",
  [anon_sym_new_line] = "new_line",
  [anon_sym_digit] = "digit",
  [anon_sym_letter] = "letter",
  [anon_sym_space] = "space",
  [anon_sym_CARET] = "^",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_rule] = "rule",
  [sym_alternative] = "alternative",
  [sym_rhs] = "rhs",
  [sym_symbol_with_procedure] = "symbol_with_procedure",
  [sym_procedure_tail] = "procedure_tail",
  [sym_double_quoted_terminal] = "double_quoted_terminal",
  [sym_single_quoted_terminal] = "single_quoted_terminal",
  [sym_generative_terminal] = "generative_terminal",
  [sym_generative_name] = "generative_name",
  [sym_exception] = "exception",
  [sym_terminal] = "terminal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_rhs_repeat1] = "rhs_repeat1",
  [aux_sym_procedure_tail_repeat1] = "procedure_tail_repeat1",
  [aux_sym_double_quoted_terminal_repeat1] = "double_quoted_terminal_repeat1",
  [aux_sym_single_quoted_terminal_repeat1] = "single_quoted_terminal_repeat1",
  [aux_sym_generative_terminal_repeat1] = "generative_terminal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_variable_symbol] = sym_variable_symbol,
  [anon_sym_AT] = anon_sym_AT,
  [sym_procedure_name] = sym_procedure_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_quoted_terminal_token1] = aux_sym_double_quoted_terminal_token1,
  [aux_sym_double_quoted_terminal_token2] = aux_sym_double_quoted_terminal_token2,
  [aux_sym_double_quoted_terminal_token3] = aux_sym_double_quoted_terminal_token3,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_quoted_terminal_token1] = aux_sym_single_quoted_terminal_token1,
  [anon_sym_ETX] = anon_sym_ETX,
  [anon_sym_lowercase_letter] = anon_sym_lowercase_letter,
  [anon_sym_uppercase_letter] = anon_sym_uppercase_letter,
  [anon_sym_block_start] = anon_sym_block_start,
  [anon_sym_block_end] = anon_sym_block_end,
  [anon_sym_whitespace] = anon_sym_whitespace,
  [anon_sym_punctuation] = anon_sym_punctuation,
  [anon_sym_character] = anon_sym_character,
  [anon_sym_operator] = anon_sym_operator,
  [anon_sym_new_line] = anon_sym_new_line,
  [anon_sym_digit] = anon_sym_digit,
  [anon_sym_letter] = anon_sym_letter,
  [anon_sym_space] = anon_sym_space,
  [anon_sym_CARET] = anon_sym_CARET,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_rule] = sym_rule,
  [sym_alternative] = sym_alternative,
  [sym_rhs] = sym_rhs,
  [sym_symbol_with_procedure] = sym_symbol_with_procedure,
  [sym_procedure_tail] = sym_procedure_tail,
  [sym_double_quoted_terminal] = sym_double_quoted_terminal,
  [sym_single_quoted_terminal] = sym_single_quoted_terminal,
  [sym_generative_terminal] = sym_generative_terminal,
  [sym_generative_name] = sym_generative_name,
  [sym_exception] = sym_exception,
  [sym_terminal] = sym_terminal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_rhs_repeat1] = aux_sym_rhs_repeat1,
  [aux_sym_procedure_tail_repeat1] = aux_sym_procedure_tail_repeat1,
  [aux_sym_double_quoted_terminal_repeat1] = aux_sym_double_quoted_terminal_repeat1,
  [aux_sym_single_quoted_terminal_repeat1] = aux_sym_single_quoted_terminal_repeat1,
  [aux_sym_generative_terminal_repeat1] = aux_sym_generative_terminal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_procedure_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_quoted_terminal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ETX] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lowercase_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uppercase_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block_start] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_whitespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_punctuation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_character] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_operator] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_new_line] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_digit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_letter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_space] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol_with_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_terminal] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_terminal] = {
    .visible = true,
    .named = true,
  },
  [sym_generative_terminal] = {
    .visible = true,
    .named = true,
  },
  [sym_generative_name] = {
    .visible = true,
    .named = true,
  },
  [sym_exception] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rhs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_procedure_tail_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quoted_terminal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_quoted_terminal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_generative_terminal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_name = 2,
  field_procedure = 3,
  field_symbol = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_name] = "name",
  [field_procedure] = "procedure",
  [field_symbol] = "symbol",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 3},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0, .inherited = true},
  [1] =
    {field_alternative, 0},
  [2] =
    {field_alternative, 2, .inherited = true},
    {field_name, 0},
  [4] =
    {field_name, 1},
  [5] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [7] =
    {field_symbol, 0},
  [8] =
    {field_name, 0},
  [9] =
    {field_symbol, 0, .inherited = true},
  [10] =
    {field_alternative, 0, .inherited = true},
    {field_alternative, 1, .inherited = true},
  [12] =
    {field_alternative, 3, .inherited = true},
    {field_name, 0},
    {field_procedure, 1},
  [15] =
    {field_procedure, 1},
  [16] =
    {field_symbol, 0, .inherited = true},
    {field_symbol, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(101);
      ADVANCE_MAP(
        0x03, 119,
        '\n', 102,
        '"', 110,
        '#', 103,
        '\'', 116,
        '@', 108,
        '\\', 98,
        '^', 132,
        '_', 100,
        'b', 51,
        'c', 43,
        'd', 45,
        'l', 24,
        'n', 29,
        'o', 62,
        'p', 94,
        's', 63,
        'u', 64,
        'w', 44,
        '|', 106,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(107);
      END_STATE();
    case 1:
      if (lookahead == 0x03) ADVANCE(119);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0) ADVANCE(117);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(98);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0) ADVANCE(114);
      END_STATE();
    case 3:
      if (lookahead == '_') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '_') ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == '_') ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(75);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(82);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(123);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(84);
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(124);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(55);
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 42:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(7);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(60);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(87);
      END_STATE();
    case 50:
      if (lookahead == 'k') ADVANCE(3);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(125);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 62:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 63:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 64:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 65:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 66:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(130);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(127);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(126);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(120);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(121);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 77:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 79:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(129);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(122);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 95:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 96:
      if (lookahead == 'w') ADVANCE(4);
      END_STATE();
    case 97:
      if (lookahead == 'w') ADVANCE(30);
      END_STATE();
    case 98:
      if (lookahead == 'x') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(112);
      END_STATE();
    case 99:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(99);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 100:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(107);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_variable_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_procedure_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token2);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(111);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token3);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_double_quoted_terminal_token3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(114);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_single_quoted_terminal_token1);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_single_quoted_terminal_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != 0x03) ADVANCE(117);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_ETX);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_lowercase_letter);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_uppercase_letter);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_block_start);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_block_end);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_whitespace);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_punctuation);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_character);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_operator);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_new_line);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_digit);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_letter);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_space);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 99},
  [46] = {.lex_state = 104},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_variable_symbol] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_double_quoted_terminal_token1] = ACTIONS(1),
    [aux_sym_double_quoted_terminal_token2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_ETX] = ACTIONS(1),
    [anon_sym_lowercase_letter] = ACTIONS(1),
    [anon_sym_uppercase_letter] = ACTIONS(1),
    [anon_sym_block_start] = ACTIONS(1),
    [anon_sym_block_end] = ACTIONS(1),
    [anon_sym_whitespace] = ACTIONS(1),
    [anon_sym_punctuation] = ACTIONS(1),
    [anon_sym_character] = ACTIONS(1),
    [anon_sym_operator] = ACTIONS(1),
    [anon_sym_new_line] = ACTIONS(1),
    [anon_sym_digit] = ACTIONS(1),
    [anon_sym_letter] = ACTIONS(1),
    [anon_sym_space] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(48),
    [sym_comment] = STATE(26),
    [sym_rule] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_variable_symbol] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_rhs] = STATE(44),
    [sym_symbol_with_procedure] = STATE(20),
    [sym_procedure_tail] = STATE(3),
    [sym_double_quoted_terminal] = STATE(9),
    [sym_single_quoted_terminal] = STATE(9),
    [sym_generative_terminal] = STATE(9),
    [sym_generative_name] = STATE(6),
    [aux_sym_rhs_repeat1] = STATE(4),
    [aux_sym_procedure_tail_repeat1] = STATE(12),
    [anon_sym_LF] = ACTIONS(11),
    [sym_variable_symbol] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_SQUOTE] = ACTIONS(19),
    [anon_sym_lowercase_letter] = ACTIONS(21),
    [anon_sym_uppercase_letter] = ACTIONS(21),
    [anon_sym_block_start] = ACTIONS(21),
    [anon_sym_block_end] = ACTIONS(21),
    [anon_sym_whitespace] = ACTIONS(21),
    [anon_sym_punctuation] = ACTIONS(21),
    [anon_sym_character] = ACTIONS(21),
    [anon_sym_operator] = ACTIONS(21),
    [anon_sym_new_line] = ACTIONS(21),
    [anon_sym_digit] = ACTIONS(21),
    [anon_sym_letter] = ACTIONS(21),
    [anon_sym_space] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(13), 1,
      sym_variable_symbol,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_LF,
    STATE(4), 1,
      aux_sym_rhs_repeat1,
    STATE(6), 1,
      sym_generative_name,
    STATE(20), 1,
      sym_symbol_with_procedure,
    STATE(47), 1,
      sym_rhs,
    STATE(9), 3,
      sym_double_quoted_terminal,
      sym_single_quoted_terminal,
      sym_generative_terminal,
    ACTIONS(21), 12,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [44] = 9,
    ACTIONS(13), 1,
      sym_variable_symbol,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      anon_sym_LF,
    STATE(5), 1,
      aux_sym_rhs_repeat1,
    STATE(6), 1,
      sym_generative_name,
    STATE(20), 1,
      sym_symbol_with_procedure,
    STATE(9), 3,
      sym_double_quoted_terminal,
      sym_single_quoted_terminal,
      sym_generative_terminal,
    ACTIONS(21), 12,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [85] = 9,
    ACTIONS(27), 1,
      anon_sym_LF,
    ACTIONS(29), 1,
      sym_variable_symbol,
    ACTIONS(32), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    STATE(5), 1,
      aux_sym_rhs_repeat1,
    STATE(6), 1,
      sym_generative_name,
    STATE(20), 1,
      sym_symbol_with_procedure,
    STATE(9), 3,
      sym_double_quoted_terminal,
      sym_single_quoted_terminal,
      sym_generative_terminal,
    ACTIONS(38), 12,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [126] = 3,
    ACTIONS(43), 1,
      anon_sym_CARET,
    STATE(7), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(41), 17,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [153] = 3,
    ACTIONS(43), 1,
      anon_sym_CARET,
    STATE(8), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(45), 17,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [180] = 3,
    ACTIONS(49), 1,
      anon_sym_CARET,
    STATE(8), 2,
      sym_exception,
      aux_sym_generative_terminal_repeat1,
    ACTIONS(47), 17,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [207] = 4,
    ACTIONS(15), 1,
      anon_sym_AT,
    STATE(12), 1,
      aux_sym_procedure_tail_repeat1,
    STATE(21), 1,
      sym_procedure_tail,
    ACTIONS(52), 16,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [235] = 3,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(10), 1,
      aux_sym_procedure_tail_repeat1,
    ACTIONS(54), 16,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [260] = 1,
    ACTIONS(59), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [281] = 3,
    ACTIONS(15), 1,
      anon_sym_AT,
    STATE(10), 1,
      aux_sym_procedure_tail_repeat1,
    ACTIONS(61), 16,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [306] = 1,
    ACTIONS(63), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [327] = 1,
    ACTIONS(65), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [348] = 1,
    ACTIONS(67), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [369] = 1,
    ACTIONS(69), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [390] = 1,
    ACTIONS(71), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [411] = 1,
    ACTIONS(73), 18,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
      anon_sym_CARET,
  [432] = 1,
    ACTIONS(75), 17,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_AT,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [452] = 1,
    ACTIONS(77), 16,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [471] = 1,
    ACTIONS(79), 16,
      anon_sym_LF,
      sym_variable_symbol,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_lowercase_letter,
      anon_sym_uppercase_letter,
      anon_sym_block_start,
      anon_sym_block_end,
      anon_sym_whitespace,
      anon_sym_punctuation,
      anon_sym_character,
      anon_sym_operator,
      anon_sym_new_line,
      anon_sym_digit,
      anon_sym_letter,
      anon_sym_space,
  [490] = 6,
    ACTIONS(83), 1,
      anon_sym_LF,
    ACTIONS(86), 1,
      anon_sym_POUND,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      sym_alternative,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(22), 2,
      sym_comment,
      aux_sym_rule_repeat1,
  [511] = 6,
    ACTIONS(94), 1,
      anon_sym_LF,
    ACTIONS(97), 1,
      anon_sym_POUND,
    ACTIONS(100), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      sym_alternative,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(22), 2,
      sym_comment,
      aux_sym_rule_repeat1,
  [532] = 6,
    ACTIONS(100), 1,
      anon_sym_PIPE,
    ACTIONS(104), 1,
      anon_sym_LF,
    ACTIONS(107), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_alternative,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      sym_variable_symbol,
    STATE(22), 2,
      sym_comment,
      aux_sym_rule_repeat1,
  [553] = 5,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      anon_sym_LF,
    ACTIONS(115), 1,
      anon_sym_POUND,
    ACTIONS(118), 1,
      sym_variable_symbol,
    STATE(25), 3,
      sym_comment,
      sym_rule,
      aux_sym_source_file_repeat1,
  [571] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_variable_symbol,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 1,
      anon_sym_LF,
    STATE(25), 3,
      sym_comment,
      sym_rule,
      aux_sym_source_file_repeat1,
  [589] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(100), 1,
      anon_sym_PIPE,
    ACTIONS(125), 1,
      anon_sym_LF,
    STATE(29), 1,
      sym_alternative,
    STATE(24), 2,
      sym_comment,
      aux_sym_rule_repeat1,
  [606] = 5,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(100), 1,
      anon_sym_PIPE,
    ACTIONS(127), 1,
      anon_sym_LF,
    STATE(29), 1,
      sym_alternative,
    STATE(23), 2,
      sym_comment,
      aux_sym_rule_repeat1,
  [623] = 1,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [631] = 4,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      aux_sym_double_quoted_terminal_token3,
    STATE(36), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(133), 2,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
  [645] = 1,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [653] = 4,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      sym_terminal,
    STATE(17), 2,
      sym_double_quoted_terminal,
      sym_single_quoted_terminal,
  [667] = 1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [675] = 1,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [683] = 1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [691] = 4,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      aux_sym_double_quoted_terminal_token3,
    STATE(36), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(147), 2,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
  [705] = 1,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_POUND,
      anon_sym_PIPE,
      sym_variable_symbol,
  [713] = 4,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      aux_sym_double_quoted_terminal_token3,
    STATE(30), 1,
      aux_sym_double_quoted_terminal_repeat1,
    ACTIONS(157), 2,
      aux_sym_double_quoted_terminal_token1,
      aux_sym_double_quoted_terminal_token2,
  [727] = 4,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(161), 1,
      anon_sym_LF,
    STATE(12), 1,
      aux_sym_procedure_tail_repeat1,
    STATE(43), 1,
      sym_procedure_tail,
  [740] = 3,
    ACTIONS(163), 1,
      aux_sym_single_quoted_terminal_token1,
    ACTIONS(165), 1,
      anon_sym_ETX,
    STATE(41), 1,
      aux_sym_single_quoted_terminal_repeat1,
  [750] = 3,
    ACTIONS(167), 1,
      aux_sym_single_quoted_terminal_token1,
    ACTIONS(169), 1,
      anon_sym_ETX,
    STATE(42), 1,
      aux_sym_single_quoted_terminal_repeat1,
  [760] = 3,
    ACTIONS(171), 1,
      aux_sym_single_quoted_terminal_token1,
    ACTIONS(174), 1,
      anon_sym_ETX,
    STATE(42), 1,
      aux_sym_single_quoted_terminal_repeat1,
  [770] = 1,
    ACTIONS(176), 1,
      anon_sym_LF,
  [774] = 1,
    ACTIONS(178), 1,
      anon_sym_LF,
  [778] = 1,
    ACTIONS(180), 1,
      sym_procedure_name,
  [782] = 1,
    ACTIONS(182), 1,
      aux_sym_comment_token1,
  [786] = 1,
    ACTIONS(184), 1,
      anon_sym_LF,
  [790] = 1,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 85,
  [SMALL_STATE(6)] = 126,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 207,
  [SMALL_STATE(10)] = 235,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 281,
  [SMALL_STATE(13)] = 306,
  [SMALL_STATE(14)] = 327,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 369,
  [SMALL_STATE(17)] = 390,
  [SMALL_STATE(18)] = 411,
  [SMALL_STATE(19)] = 432,
  [SMALL_STATE(20)] = 452,
  [SMALL_STATE(21)] = 471,
  [SMALL_STATE(22)] = 490,
  [SMALL_STATE(23)] = 511,
  [SMALL_STATE(24)] = 532,
  [SMALL_STATE(25)] = 553,
  [SMALL_STATE(26)] = 571,
  [SMALL_STATE(27)] = 589,
  [SMALL_STATE(28)] = 606,
  [SMALL_STATE(29)] = 623,
  [SMALL_STATE(30)] = 631,
  [SMALL_STATE(31)] = 645,
  [SMALL_STATE(32)] = 653,
  [SMALL_STATE(33)] = 667,
  [SMALL_STATE(34)] = 675,
  [SMALL_STATE(35)] = 683,
  [SMALL_STATE(36)] = 691,
  [SMALL_STATE(37)] = 705,
  [SMALL_STATE(38)] = 713,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 740,
  [SMALL_STATE(41)] = 750,
  [SMALL_STATE(42)] = 760,
  [SMALL_STATE(43)] = 770,
  [SMALL_STATE(44)] = 774,
  [SMALL_STATE(45)] = 778,
  [SMALL_STATE(46)] = 782,
  [SMALL_STATE(47)] = 786,
  [SMALL_STATE(48)] = 790,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rhs, 1, 0, 8),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 12),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 12), SHIFT_REPEAT(9),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 12), SHIFT_REPEAT(38),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 12), SHIFT_REPEAT(40),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 2, 0, 12), SHIFT_REPEAT(11),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_terminal, 1, 0, 7),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_terminal, 2, 0, 7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_generative_terminal_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_generative_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_with_procedure, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_procedure_tail_repeat1, 2, 0, 5),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_procedure_tail_repeat1, 2, 0, 5), SHIFT_REPEAT(45),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generative_name, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_tail, 1, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_terminal, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_terminal, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_terminal, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_terminal, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exception, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_procedure_tail_repeat1, 2, 0, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rhs_repeat1, 1, 0, 6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol_with_procedure, 2, 0, 11),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 9),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 9), SHIFT_REPEAT(22),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 9), SHIFT_REPEAT(46),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 9), SHIFT_REPEAT(2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 10),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 4, 0, 10), SHIFT(22),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 4, 0, 10), SHIFT(46),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3), SHIFT(22),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_rule, 3, 0, 3), SHIFT(46),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 1, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3, 0, 11),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_quoted_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 4, 0, 11),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_quoted_terminal_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_quoted_terminal_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_galley(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "galley",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
